#!/bin/sh
eval $(cat makeinclude | grep = | sed -e "s/\\$/\\\\$/g;s/ = /=\"/" | sed -e "s/$/\"/")

echo "#define INCLUDES \"$INCLUDES\"" > compilerflags.h
echo "#define LIBS \"$LIBS\"" >> compilerflags.h

